package com.starbooks.model;
// Generated 2015/10/30 �U�� 03:00:03 by Hibernate Tools 4.3.1.Final

/**
 * BookAuthor generated by hbm2java
 */
public class BookAuthor implements java.io.Serializable {

	private BookAuthorId id;

	public BookAuthor() {
	}

	public BookAuthor(BookAuthorId id) {
		this.id = id;
	}

	public BookAuthorId getId() {
		return this.id;
	}

	public void setId(BookAuthorId id) {
		this.id = id;
	}

}
