package com.starbooks.model;
// Generated 2015/10/30 �U�� 03:00:03 by Hibernate Tools 4.3.1.Final

/**
 * BookAuthorId generated by hbm2java
 */
public class BookAuthorId implements java.io.Serializable {

	private int bkId;
	private int arId;

	public BookAuthorId() {
	}

	public BookAuthorId(int bkId, int arId) {
		this.bkId = bkId;
		this.arId = arId;
	}

	public int getBkId() {
		return this.bkId;
	}

	public void setBkId(int bkId) {
		this.bkId = bkId;
	}

	public int getArId() {
		return this.arId;
	}

	public void setArId(int arId) {
		this.arId = arId;
	}

}
